name: Publish selected development build
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Setup dotnet tools
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Restore NPM packages
        working-directory: ./BytexDigital.Blazor.Components.CookieConsent
        run: npm install --only=dev

      - name: Build CSS
        working-directory: ./BytexDigital.Blazor.Components.CookieConsent
        run: npm run build
        
      - name: Remove NPM artifacts
        working-directory: ./BytexDigital.Blazor.Components.CookieConsent
        run: |
          rm -fr node_modules
          rm -f package.json
          rm -f package-lock.json

      # - name: Build project
      #   run: dotnet build -c Release -p:VersionSuffix=development.$(date +%s)
      - name: Build project with alternative assembly name
        run: dotnet build build.slnf -c Release -p:VersionSuffix=preview.$(date +%s) -p:OverwriteAssemblyName=CC

      - name: Push project
        run: dotnet nuget push **/*.nupkg -s ${{secrets.GH_NUGET_FEED_URL}} -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate